# Generated by Django 3.0.6 on 2020-07-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msalumnidetail',
            name='FK_major_name',
        ),
        migrations.AddField(
            model_name='msalumnidetail',
            name='FK_major_name',
            field=models.ManyToManyField(to='app.MSMajorList'),
        ),
    ]
