# Generated by Django 3.0.6 on 2020-07-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200716_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSBlogSubcriberList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(editable=False, max_length=255)),
            ],
        ),
    ]
