# Generated by Django 3.0.6 on 2020-07-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_msblogsubcriberlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msmajorlist',
            name='FK_school_name',
        ),
        migrations.AddField(
            model_name='msschoollist',
            name='FK_major_name',
            field=models.ManyToManyField(to='app.MSMajorList'),
        ),
    ]
